### ISSUE TITLE
setSkipNulls , setSkipEmpty seems not working as expected.

### ISSUE THREAD

**Issue by py1971** [arakelian/json-filter#3]
setSkipNulls , setSkipEmpty seems not working on '3.7.0'.

writer.withSkipNulls(true).withSkipEmpty(true).withPretty(false);

Only Pretty worked as expected.

Thank you!

**Comment by py1971** [comment]
@Test
    public void testIncludeSimple1() throws IOException {
        final String json = "" + //
                "{\n" + //
                "    \"empty\": \"\",\n" + //
                "    \"id\": 1,\n" + //
                "    \"name\": \"A green door\",\n" + //
                "    \"price\": 12.50,\n" + //
                "    \"tags\": [\"home\", \"green\"],\n" + //
                "        \"zoo\": null\n" + //
                "}";
        final String expected = "" + //
                "{\n" + //
                "  \"name\" : \"A green door\"\n" + //
                "}";

        System.out.println("=== original json ===>\n" + json);
        System.out.println("=== expected json ===>\n" + expected); 
        JsonFilterOptions opts = ImmutableJsonFilterOptions.builder() //
                .addIncludes("empty", "name", "zoo") //
                .build();

        StringWriter sw = new StringWriter();
        JsonReader reader = new JsonReader(json);
        JsonWriter<StringWriter> writer = new JsonWriter<StringWriter>(sw);
        writer.withSkipNulls(true).withSkipEmpty(true);                        
        // writer.setPretty(true);
        // execute filter
        JsonFilter filter = new JsonFilter(reader,writer,opts);
        filter.process();
        String result = sw.toString();
        System.out.println("=== processed json ===>\n" + result);             
        assertEquals(
                expected,
                result);
    }
////////////. Thank you!  .////////////

**Comment by arakelian** [comment]
I'll need to make some enhancements to JsonWriter to support this use case.  JsonWriter currently only omits null/empty values when it receives both the key and value at the same time (JsonWriter.writeKeyValue) -- unfortunately, JsonFilter is fully streaming and sends the key and value separately.  I could either improve the Javadocs to make this more clear, or make improvements to JsonWriter.  After thinking about it, and looking at the code, I think this is good case to support. I'll add over the next few days.  Thanks for nice unit test.

**Comment by py1971** [comment]
Thanks for Arakelian’s information!
Your artifact on this project does help me to facilitate the JSON processing based on some frequent modified configurations on the resources.

Might we consider to have skipNulls / skipEmpty in the JsonReader / JsonFilterOptions , right?
During JsonReader parsing the JSON document, maybe it is possibly easier to get rids of Nulls and Empty ?

Again, Thanks for your great efforts on this OSS project!

**Comment by arakelian** [comment]
Fixed in 3.9.1
